github:
  token: your_token

courses:
  - name: BSYS
    organization: htwg-syslab-bsys
    repo_regex: bsys-(ss|ws)\d{2}-grp\d+
  - name: SYSO
    organization: htwg-syslab-syso
    repo_regex: syso-(ss|ws)\d{2}-grp\d+
